### ISSUE TITLE
Session token in source code

### ISSUE THREAD

**Issue by FlorianCassayre** [emilwihlander/adventofcode#1]
Hi Emil, the leaderboard is very neat.
However I noticed that you hardcoded a session token in the source code (`visualizer/download.js`). This is generally not a good idea, especially if the repository is public and the token is linked to an account you are using. (this essentially grants anyone full access to your account, as long as the session is active)
Consider storing this value in an environment variable instead. Since you are using GitHub Actions, you may set a [secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets) to inject it when the script is run. If you need any help to achieve that let me know, I'll be happy to do so.
Unfortunately some forks are also affected and will have to perform similar changes.

**Comment by FlorianCassayre** [comment]
@emilwihlander This is important and needs to be addressed as soon as you can.
If no action is taken I will invalidate this session cookie myself to prevent unauthorized uses.

**Comment by emilwihlander** [comment]
Thanks for the heads up! This should be fixed in this repo at least, as I amended to only commit with the active session token and moved it to the secrets store. I'll contact the owners of any fork that contain the active session token.

**Comment by FlorianCassayre** [comment]
Great job, looks good! :100: 

Also note that the existing token remains valid for about a month, unless you log out from that session. Therefore I would also suggest to log out and back in to invalidate the previous token, if that has not been done already.

**Comment by emilwihlander** [comment]
It's not my token, unfortunately. @niklashedstrom could you logout and add the new token to the secrets store?

**Comment by FlorianCassayre** [comment]
np -- I'll do it.
